# coding: utf-8

"""
    Vimeo API

    Build something great. Vimeo's API supports flexible, high-quality video integration with your custom apps.

    The version of the OpenAPI document: 3.4
    Created by: https://developer.vimeo.com/help
"""

from vimeo_python_sdk.paths.oauth_authorize_client.post import Auth
from vimeo_python_sdk.apis.tags.authentication_extras_authenticate_api_raw import AuthenticationExtrasAuthenticateApiRaw


class AuthenticationExtrasAuthenticateApi(
    Auth,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: AuthenticationExtrasAuthenticateApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = AuthenticationExtrasAuthenticateApiRaw(api_client)
