# coding: utf-8

"""
    Vimeo API

    Build something great. Vimeo's API supports flexible, high-quality video integration with your custom apps.

    The version of the OpenAPI document: 3.4
    Created by: https://developer.vimeo.com/help
"""

from vimeo_python_sdk.paths.videos_video_id_categories.get import GetAllVideoCategoriesRaw
from vimeo_python_sdk.paths.categories_category_videos_video_id.get import GetVideoInCategoryRaw
from vimeo_python_sdk.paths.categories_category_videos.get import ListVideosInCategoryRaw
from vimeo_python_sdk.paths.videos_video_id_categories.put import SetVideoCategoriesRaw


class CategoriesVideosApiRaw(
    GetAllVideoCategoriesRaw,
    GetVideoInCategoryRaw,
    ListVideosInCategoryRaw,
    SetVideoCategoriesRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
