# coding: utf-8

"""
    Vimeo API

    Build something great. Vimeo's API supports flexible, high-quality video integration with your custom apps.

    The version of the OpenAPI document: 3.4
    Created by: https://developer.vimeo.com/help
"""

from vimeo_python_sdk.paths.me_categories_category.get import CheckFollowedCategoryRaw
from vimeo_python_sdk.paths.users_user_id_categories_category.get import CheckFollowedCategory0Raw
from vimeo_python_sdk.paths.me_categories_category.put import FollowCategoryRaw
from vimeo_python_sdk.paths.users_user_id_categories_category.put import FollowSpecificCategoryRaw
from vimeo_python_sdk.paths.me_categories.get import ListFollowedCategoriesRaw
from vimeo_python_sdk.paths.users_user_id_categories.get import ListFollowedCategories0Raw
from vimeo_python_sdk.paths.me_categories_category.delete import StopFollowingCategoryRaw
from vimeo_python_sdk.paths.users_user_id_categories_category.delete import StopFollowingCategory0Raw


class CategoriesUsersApiRaw(
    CheckFollowedCategoryRaw,
    CheckFollowedCategory0Raw,
    FollowCategoryRaw,
    FollowSpecificCategoryRaw,
    ListFollowedCategoriesRaw,
    ListFollowedCategories0Raw,
    StopFollowingCategoryRaw,
    StopFollowingCategory0Raw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
