# coding: utf-8

"""
    Vimeo API

    Build something great. Vimeo's API supports flexible, high-quality video integration with your custom apps.

    The version of the OpenAPI document: 3.4
    Created by: https://developer.vimeo.com/help
"""

from vimeo_python_sdk.paths.channels_channel_id_tags.put import AddMultipleTagsToChannelRaw
from vimeo_python_sdk.paths.channels_channel_id_tags_word.put import AddTagToChannelRaw
from vimeo_python_sdk.paths.channels_channel_id_tags_word.get import CheckIfTagAddedToChannelRaw
from vimeo_python_sdk.paths.channels_channel_id_tags.get import GetAllChannelTagsRaw
from vimeo_python_sdk.paths.channels_channel_id_tags_word.delete import RemoveTagFromChannelRaw


class ChannelsTagsApiRaw(
    AddMultipleTagsToChannelRaw,
    AddTagToChannelRaw,
    CheckIfTagAddedToChannelRaw,
    GetAllChannelTagsRaw,
    RemoveTagFromChannelRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
