# coding: utf-8

"""
    Vimeo API

    Build something great. Vimeo's API supports flexible, high-quality video integration with your custom apps.

    The version of the OpenAPI document: 3.4
    Created by: https://developer.vimeo.com/help
"""

from vimeo_python_sdk.paths.channels.post import ChannelRaw
from vimeo_python_sdk.paths.channels_channel_id.get import Channel0Raw
from vimeo_python_sdk.paths.channels_channel_id.delete import Channel1Raw
from vimeo_python_sdk.paths.channels_channel_id.patch import Channel2Raw
from vimeo_python_sdk.paths.channels.get import ChannelsRaw
from vimeo_python_sdk.paths.me_channels.get import GetUserSubscriptionsRaw
from vimeo_python_sdk.paths.users_user_id_channels.get import GetUserSubscriptions0Raw


class ChannelsEssentialsApiRaw(
    ChannelRaw,
    Channel0Raw,
    Channel1Raw,
    Channel2Raw,
    ChannelsRaw,
    GetUserSubscriptionsRaw,
    GetUserSubscriptions0Raw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
