# coding: utf-8

"""
    Vimeo API

    Build something great. Vimeo's API supports flexible, high-quality video integration with your custom apps.

    The version of the OpenAPI document: 3.4
    Created by: https://developer.vimeo.com/help
"""

from vimeo_python_sdk.paths.channels.post import Channel
from vimeo_python_sdk.paths.channels_channel_id.get import Channel0
from vimeo_python_sdk.paths.channels_channel_id.delete import Channel1
from vimeo_python_sdk.paths.channels_channel_id.patch import Channel2
from vimeo_python_sdk.paths.channels.get import Channels
from vimeo_python_sdk.paths.me_channels.get import GetUserSubscriptions
from vimeo_python_sdk.paths.users_user_id_channels.get import GetUserSubscriptions0
from vimeo_python_sdk.apis.tags.channels_essentials_api_raw import ChannelsEssentialsApiRaw


class ChannelsEssentialsApi(
    Channel,
    Channel0,
    Channel1,
    Channel2,
    Channels,
    GetUserSubscriptions,
    GetUserSubscriptions0,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: ChannelsEssentialsApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = ChannelsEssentialsApiRaw(api_client)
