# coding: utf-8

"""
    Vimeo API

    Build something great. Vimeo's API supports flexible, high-quality video integration with your custom apps.

    The version of the OpenAPI document: 3.4
    Created by: https://developer.vimeo.com/help
"""

from vimeo_python_sdk.paths.users_user_id_presets.post import CreateEmbedPreset
from vimeo_python_sdk.paths.me_presets.post import CreatePreset
from vimeo_python_sdk.paths.me_presets_preset_id.patch import EditPreset
from vimeo_python_sdk.paths.users_user_id_presets_preset_id.patch import EditPreset0
from vimeo_python_sdk.paths.me_presets.get import GetAllUserCreatedEmbedPresets
from vimeo_python_sdk.paths.users_user_id_presets_preset_id.get import GetSpecificEmbedPreset
from vimeo_python_sdk.paths.me_presets_preset_id.get import GetSpecificPreset
from vimeo_python_sdk.paths.users_user_id_presets.get import GetUserEmbedPresets
from vimeo_python_sdk.apis.tags.embed_presets_essentials_api_raw import EmbedPresetsEssentialsApiRaw


class EmbedPresetsEssentialsApi(
    CreateEmbedPreset,
    CreatePreset,
    EditPreset,
    EditPreset0,
    GetAllUserCreatedEmbedPresets,
    GetSpecificEmbedPreset,
    GetSpecificPreset,
    GetUserEmbedPresets,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: EmbedPresetsEssentialsApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = EmbedPresetsEssentialsApiRaw(api_client)
