# coding: utf-8

"""
    Vimeo API

    Build something great. Vimeo's API supports flexible, high-quality video integration with your custom apps.

    The version of the OpenAPI document: 3.4
    Created by: https://developer.vimeo.com/help
"""

from vimeo_python_sdk.paths.me_projects_project_id_videos.put import AddMultipleToFolder
from vimeo_python_sdk.paths.users_user_id_projects_project_id_videos_video_id.put import AddSingleFolderVideo
from vimeo_python_sdk.paths.me_projects_project_id_videos_video_id.put import AddToFolder
from vimeo_python_sdk.paths.users_user_id_projects_project_id_videos.put import AddToFolderVideos
from vimeo_python_sdk.paths.users_user_id_projects_project_id_videos.get import GetAllFolderVideos
from vimeo_python_sdk.paths.me_projects_project_id_videos.get import GetVideosInFolder
from vimeo_python_sdk.paths.users_user_id_projects_project_id_videos_video_id.delete import RemoveFromFolderVideo
from vimeo_python_sdk.paths.me_projects_project_id_videos.delete import RemoveMultipleFromFolder
from vimeo_python_sdk.paths.users_user_id_projects_project_id_videos.delete import RemoveMultipleVideosFromFolder
from vimeo_python_sdk.paths.me_projects_project_id_videos_video_id.delete import RemoveSingleVideo
from vimeo_python_sdk.apis.tags.folders_videos_api_raw import FoldersVideosApiRaw


class FoldersVideosApi(
    AddMultipleToFolder,
    AddSingleFolderVideo,
    AddToFolder,
    AddToFolderVideos,
    GetAllFolderVideos,
    GetVideosInFolder,
    RemoveFromFolderVideo,
    RemoveMultipleFromFolder,
    RemoveMultipleVideosFromFolder,
    RemoveSingleVideo,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: FoldersVideosApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = FoldersVideosApiRaw(api_client)
