# coding: utf-8

"""
    Vimeo API

    Build something great. Vimeo's API supports flexible, high-quality video integration with your custom apps.

    The version of the OpenAPI document: 3.4
    Created by: https://developer.vimeo.com/help
"""

from vimeo_python_sdk.paths.users_user_id_projects_project_id_items.get import GetFolderContentsRaw
from vimeo_python_sdk.paths.me_projects_project_id_items.get import GetFolderItemsRaw
from vimeo_python_sdk.paths.me_projects_project_id_items.delete import RemoveFromFolderRaw


class FoldersItemsApiRaw(
    GetFolderContentsRaw,
    GetFolderItemsRaw,
    RemoveFromFolderRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
