# coding: utf-8

"""
    Vimeo API

    Build something great. Vimeo's API supports flexible, high-quality video integration with your custom apps.

    The version of the OpenAPI document: 3.4
    Created by: https://developer.vimeo.com/help
"""

from vimeo_python_sdk.paths.users_user_id_groups_group_id.get import CheckBelongGroupRaw
from vimeo_python_sdk.paths.me_groups_group_id.get import CheckUserJoinedGroupRaw
from vimeo_python_sdk.paths.groups_group_id_users.get import GetGroupUsersRaw
from vimeo_python_sdk.paths.me_groups.get import GetUserGroupsRaw
from vimeo_python_sdk.paths.users_user_id_groups.get import GetUserGroupsListRaw


class GroupsUsersApiRaw(
    CheckBelongGroupRaw,
    CheckUserJoinedGroupRaw,
    GetGroupUsersRaw,
    GetUserGroupsRaw,
    GetUserGroupsListRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
