# coding: utf-8

"""
    Vimeo API

    Build something great. Vimeo's API supports flexible, high-quality video integration with your custom apps.

    The version of the OpenAPI document: 3.4
    Created by: https://developer.vimeo.com/help
"""

from vimeo_python_sdk.paths.me_likes_video_id.get import CheckUserLikedVideoRaw
from vimeo_python_sdk.paths.users_user_id_likes_video_id.get import CheckVideoLikedByUserRaw
from vimeo_python_sdk.paths.ondemand_pages_ondemand_id_likes.get import GetAllUserLikesRaw
from vimeo_python_sdk.paths.me_likes.get import GetUserLikedVideosRaw
from vimeo_python_sdk.paths.videos_video_id_likes.get import GetUserLikesRaw
from vimeo_python_sdk.paths.channels_channel_id_videos_video_id_likes.get import GetUsersWhoLikedVideoRaw
from vimeo_python_sdk.paths.me_likes_video_id.put import LikeVideoRaw
from vimeo_python_sdk.paths.users_user_id_likes.get import LikesRaw
from vimeo_python_sdk.paths.me_likes_video_id.delete import UnlikeVideoRaw
from vimeo_python_sdk.paths.users_user_id_likes_video_id.put import VideoRaw
from vimeo_python_sdk.paths.users_user_id_likes_video_id.delete import Video0Raw


class LikesEssentialsApiRaw(
    CheckUserLikedVideoRaw,
    CheckVideoLikedByUserRaw,
    GetAllUserLikesRaw,
    GetUserLikedVideosRaw,
    GetUserLikesRaw,
    GetUsersWhoLikedVideoRaw,
    LikeVideoRaw,
    LikesRaw,
    UnlikeVideoRaw,
    VideoRaw,
    Video0Raw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
