# coding: utf-8

"""
    Vimeo API

    Build something great. Vimeo's API supports flexible, high-quality video integration with your custom apps.

    The version of the OpenAPI document: 3.4
    Created by: https://developer.vimeo.com/help
"""

from vimeo_python_sdk.paths.live_events_live_event_id_activate.post import CreateRtmpLinks
from vimeo_python_sdk.paths.me_live_events_live_event_id_activate.post import CreateRtmpLinks0
from vimeo_python_sdk.paths.users_user_id_live_events_live_event_id_activate.post import CreateRtmpLinks1
from vimeo_python_sdk.apis.tags.live_event_activation_api_raw import LiveEventActivationApiRaw


class LiveEventActivationApi(
    CreateRtmpLinks,
    CreateRtmpLinks0,
    CreateRtmpLinks1,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: LiveEventActivationApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = LiveEventActivationApiRaw(api_client)
