# coding: utf-8

"""
    Vimeo API

    Build something great. Vimeo's API supports flexible, high-quality video integration with your custom apps.

    The version of the OpenAPI document: 3.4
    Created by: https://developer.vimeo.com/help
"""

from vimeo_python_sdk.paths.live_events_live_event_id_videos.post import AddMultiple
from vimeo_python_sdk.paths.users_user_id_live_events_live_event_id_videos.post import AddMultipleVideos
from vimeo_python_sdk.paths.me_live_events_live_event_id_videos.get import GetAll
from vimeo_python_sdk.paths.users_user_id_live_events_live_event_id_videos_video_id.get import GetSpecificVideo
from vimeo_python_sdk.paths.users_user_id_live_events_live_event_id_videos.get import ListAllVideosInEvent
from vimeo_python_sdk.paths.live_events_live_event_id_videos.get import ListLiveEventVideos
from vimeo_python_sdk.paths.me_live_events_live_event_id_videos.delete import RemoveMultiple
from vimeo_python_sdk.paths.users_user_id_live_events_live_event_id_videos.delete import RemoveMultiple0
from vimeo_python_sdk.paths.live_events_live_event_id_videos.delete import RemoveMultipleVideos
from vimeo_python_sdk.paths.live_events_live_event_id_videos_video_id.get import SpecificEventVideo
from vimeo_python_sdk.paths.me_live_events_live_event_id_videos_video_id.get import SpecificVideo
from vimeo_python_sdk.paths.me_live_events_live_event_id_videos.post import UploadMultiple
from vimeo_python_sdk.apis.tags.live_event_videos_api_raw import LiveEventVideosApiRaw


class LiveEventVideosApi(
    AddMultiple,
    AddMultipleVideos,
    GetAll,
    GetSpecificVideo,
    ListAllVideosInEvent,
    ListLiveEventVideos,
    RemoveMultiple,
    RemoveMultiple0,
    RemoveMultipleVideos,
    SpecificEventVideo,
    SpecificVideo,
    UploadMultiple,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: LiveEventVideosApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = LiveEventVideosApiRaw(api_client)
