# coding: utf-8

"""
    Vimeo API

    Build something great. Vimeo's API supports flexible, high-quality video integration with your custom apps.

    The version of the OpenAPI document: 3.4
    Created by: https://developer.vimeo.com/help
"""

from vimeo_python_sdk.paths.live_events_live_event_id_auto_cc.patch import EditPreferenceRaw
from vimeo_python_sdk.paths.me_live_events_live_event_id_auto_cc.patch import EditPreferenceForEventRaw
from vimeo_python_sdk.paths.users_user_id_live_events_live_event_id_auto_cc.patch import EditPreferenceForEvent0Raw


class LiveEventAutomatedClosedCaptionsApiRaw(
    EditPreferenceRaw,
    EditPreferenceForEventRaw,
    EditPreferenceForEvent0Raw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
