# coding: utf-8

"""
    Vimeo API

    Build something great. Vimeo's API supports flexible, high-quality video integration with your custom apps.

    The version of the OpenAPI document: 3.4
    Created by: https://developer.vimeo.com/help
"""

from vimeo_python_sdk.paths.videos_video_id_sessions_status.get import GetIngestStatus
from vimeo_python_sdk.apis.tags.live_event_sessions_api_raw import LiveEventSessionsApiRaw


class LiveEventSessionsApi(
    GetIngestStatus,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: LiveEventSessionsApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = LiveEventSessionsApiRaw(api_client)
