# coding: utf-8

"""
    Vimeo API

    Build something great. Vimeo's API supports flexible, high-quality video integration with your custom apps.

    The version of the OpenAPI document: 3.4
    Created by: https://developer.vimeo.com/help
"""

from vimeo_python_sdk.paths.ondemand_pages_ondemand_id_backgrounds.post import AddBackgroundToPage
from vimeo_python_sdk.paths.ondemand_pages_ondemand_id_backgrounds_background_id.delete import DeleteBackgroundFromPage
from vimeo_python_sdk.paths.ondemand_pages_ondemand_id_backgrounds_background_id.patch import EditBackgroundOnPage
from vimeo_python_sdk.paths.ondemand_pages_ondemand_id_backgrounds.get import GetAllBackgroundsOnPage
from vimeo_python_sdk.paths.ondemand_pages_ondemand_id_backgrounds_background_id.get import GetSpecificBackground
from vimeo_python_sdk.apis.tags.on_demand_backgrounds_api_raw import OnDemandBackgroundsApiRaw


class OnDemandBackgroundsApi(
    AddBackgroundToPage,
    DeleteBackgroundFromPage,
    EditBackgroundOnPage,
    GetAllBackgroundsOnPage,
    GetSpecificBackground,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: OnDemandBackgroundsApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = OnDemandBackgroundsApiRaw(api_client)
