# coding: utf-8

"""
    Vimeo API

    Build something great. Vimeo's API supports flexible, high-quality video integration with your custom apps.

    The version of the OpenAPI document: 3.4
    Created by: https://developer.vimeo.com/help
"""

from vimeo_python_sdk.paths.ondemand_pages_ondemand_id_seasons_season_id_videos.get import GetAllVideosInSeason
from vimeo_python_sdk.paths.ondemand_pages_ondemand_id_seasons.get import ListAll
from vimeo_python_sdk.paths.ondemand_pages_ondemand_id_seasons_season_id.get import SpecificGet
from vimeo_python_sdk.apis.tags.on_demand_seasons_api_raw import OnDemandSeasonsApiRaw


class OnDemandSeasonsApi(
    GetAllVideosInSeason,
    ListAll,
    SpecificGet,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: OnDemandSeasonsApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = OnDemandSeasonsApiRaw(api_client)
