# coding: utf-8

"""
    Vimeo API

    Build something great. Vimeo's API supports flexible, high-quality video integration with your custom apps.

    The version of the OpenAPI document: 3.4
    Created by: https://developer.vimeo.com/help
"""

from vimeo_python_sdk.paths.me_ondemand_purchases_ondemand_id.get import CheckUserPurchasesAndRentals
from vimeo_python_sdk.paths.me_ondemand_purchases.get import GetAllUserPurchasesAndRentals
from vimeo_python_sdk.paths.users_user_id_ondemand_purchases.get import ListUserPurchasesAndRentals
from vimeo_python_sdk.apis.tags.on_demand_purchases_and_rentals_api_raw import OnDemandPurchasesAndRentalsApiRaw


class OnDemandPurchasesAndRentalsApi(
    CheckUserPurchasesAndRentals,
    GetAllUserPurchasesAndRentals,
    ListUserPurchasesAndRentals,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: OnDemandPurchasesAndRentalsApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = OnDemandPurchasesAndRentalsApiRaw(api_client)
