# coding: utf-8

"""
    Vimeo API

    Build something great. Vimeo's API supports flexible, high-quality video integration with your custom apps.

    The version of the OpenAPI document: 3.4
    Created by: https://developer.vimeo.com/help
"""

from vimeo_python_sdk.paths.ondemand_pages_ondemand_id_genres_genre_id.put import AddGenreToPageRaw
from vimeo_python_sdk.paths.ondemand_pages_ondemand_id_genres_genre_id.get import CheckGenreAssociationRaw
from vimeo_python_sdk.paths.ondemand_genres.get import GetAllGenresRaw
from vimeo_python_sdk.paths.ondemand_genres_genre_id_pages.get import GetAllPagesInGenreRaw
from vimeo_python_sdk.paths.ondemand_pages_ondemand_id_genres.get import GetGenresRaw
from vimeo_python_sdk.paths.ondemand_genres_genre_id_pages_ondemand_id.get import GetSpecificPageInGenreRaw
from vimeo_python_sdk.paths.ondemand_pages_ondemand_id_genres_genre_id.delete import RemoveGenreFromPageRaw
from vimeo_python_sdk.paths.ondemand_genres_genre_id.get import SpecificGenreGetRaw


class OnDemandGenresApiRaw(
    AddGenreToPageRaw,
    CheckGenreAssociationRaw,
    GetAllGenresRaw,
    GetAllPagesInGenreRaw,
    GetGenresRaw,
    GetSpecificPageInGenreRaw,
    RemoveGenreFromPageRaw,
    SpecificGenreGetRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
