# coding: utf-8

"""
    Vimeo API

    Build something great. Vimeo's API supports flexible, high-quality video integration with your custom apps.

    The version of the OpenAPI document: 3.4
    Created by: https://developer.vimeo.com/help
"""

from vimeo_python_sdk.paths.users_user_id_portfolios_portfolio_id_videos_video_id.put import AddVideoToPortfolioRaw
from vimeo_python_sdk.paths.me_portfolios_portfolio_id_videos.get import GetAllPortfolioVideosRaw
from vimeo_python_sdk.paths.users_user_id_portfolios_portfolio_id_videos.get import GetAllPortfolioVideos0Raw
from vimeo_python_sdk.paths.me_portfolios_portfolio_id_videos_video_id.get import GetSpecificVideoRaw
from vimeo_python_sdk.paths.users_user_id_portfolios_portfolio_id_videos_video_id.get import GetSpecificVideo0Raw
from vimeo_python_sdk.paths.me_portfolios_portfolio_id_videos_video_id.put import PutVideoToPortfolioRaw
from vimeo_python_sdk.paths.me_portfolios_portfolio_id_videos_video_id.delete import RemoveFromPortfolioRaw
from vimeo_python_sdk.paths.users_user_id_portfolios_portfolio_id_videos_video_id.delete import RemoveFromPortfolioVideoRaw


class PortfoliosVideosApiRaw(
    AddVideoToPortfolioRaw,
    GetAllPortfolioVideosRaw,
    GetAllPortfolioVideos0Raw,
    GetSpecificVideoRaw,
    GetSpecificVideo0Raw,
    PutVideoToPortfolioRaw,
    RemoveFromPortfolioRaw,
    RemoveFromPortfolioVideoRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
