# coding: utf-8

"""
    Vimeo API

    Build something great. Vimeo's API supports flexible, high-quality video integration with your custom apps.

    The version of the OpenAPI document: 3.4
    Created by: https://developer.vimeo.com/help
"""

from vimeo_python_sdk.paths.users_user_id_albums_album_id_custom_thumbnails.post import AddCustomThumbnailRaw
from vimeo_python_sdk.paths.users_user_id_albums_album_id_custom_thumbnails_thumbnail_id.delete import DeleteCustomThumbnailRaw
from vimeo_python_sdk.paths.users_user_id_albums_album_id_custom_thumbnails_thumbnail_id.get import GetSpecificThumbnailRaw
from vimeo_python_sdk.paths.users_user_id_albums_album_id_custom_thumbnails.get import ListRaw
from vimeo_python_sdk.paths.users_user_id_albums_album_id_custom_thumbnails_thumbnail_id.patch import ReplaceCustomThumbnailRaw


class ShowcasesCustomShowcaseThumbnailsApiRaw(
    AddCustomThumbnailRaw,
    DeleteCustomThumbnailRaw,
    GetSpecificThumbnailRaw,
    ListRaw,
    ReplaceCustomThumbnailRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
