# coding: utf-8

"""
    Vimeo API

    Build something great. Vimeo's API supports flexible, high-quality video integration with your custom apps.

    The version of the OpenAPI document: 3.4
    Created by: https://developer.vimeo.com/help
"""

from vimeo_python_sdk.paths.users_user_id_albums_album_id_logos.post import AddCustomLogoRaw
from vimeo_python_sdk.paths.users_user_id_albums_album_id_logos_logo_id.delete import DeleteCustomLogoRaw
from vimeo_python_sdk.paths.users_user_id_albums_album_id_logos_logo_id.get import GetSpecificLogoRaw
from vimeo_python_sdk.paths.users_user_id_albums_album_id_logos.get import ListAllCustomLogosRaw
from vimeo_python_sdk.paths.users_user_id_albums_album_id_logos_logo_id.patch import ReplaceLogoRaw


class ShowcasesCustomShowcaseLogosApiRaw(
    AddCustomLogoRaw,
    DeleteCustomLogoRaw,
    GetSpecificLogoRaw,
    ListAllCustomLogosRaw,
    ReplaceLogoRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
