# coding: utf-8

"""
    Vimeo API

    Build something great. Vimeo's API supports flexible, high-quality video integration with your custom apps.

    The version of the OpenAPI document: 3.4
    Created by: https://developer.vimeo.com/help
"""

from vimeo_python_sdk.paths.teammembers_code.get import GetMembershipInformationRaw
from vimeo_python_sdk.paths.users_user_id_team_users_team_user_id.get import GetTeamMembershipInformationRaw
from vimeo_python_sdk.paths.users_user_id_team_role.get import GetUserTeamRoleRaw


class TeamsMembersApiRaw(
    GetMembershipInformationRaw,
    GetTeamMembershipInformationRaw,
    GetUserTeamRoleRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
