# coding: utf-8

"""
    Vimeo API

    Build something great. Vimeo's API supports flexible, high-quality video integration with your custom apps.

    The version of the OpenAPI document: 3.4
    Created by: https://developer.vimeo.com/help
"""

from vimeo_python_sdk.paths.users_user_id_following_follow_user_id.get import CheckFollowingStatusRaw
from vimeo_python_sdk.paths.me_following_follow_user_id.get import CheckFollowingUserRaw
from vimeo_python_sdk.paths.me_following.post import FollowMultipleUsersRaw
from vimeo_python_sdk.paths.me_following_follow_user_id.put import FollowSpecificUserRaw
from vimeo_python_sdk.paths.users_user_id_followers.get import FollowersRaw
from vimeo_python_sdk.paths.me_followers.get import ListAllRaw
from vimeo_python_sdk.paths.users_user_id_following.get import ListOfFollowedUsersRaw
from vimeo_python_sdk.paths.me_following.get import ListOfFollowingUsersRaw
from vimeo_python_sdk.paths.me_following_follow_user_id.delete import StopFollowingUserRaw
from vimeo_python_sdk.paths.users_user_id_following_follow_user_id.put import UserRaw
from vimeo_python_sdk.paths.users_user_id_following_follow_user_id.delete import User0Raw
from vimeo_python_sdk.paths.users_user_id_following.post import UsersRaw


class UsersFollowersApiRaw(
    CheckFollowingStatusRaw,
    CheckFollowingUserRaw,
    FollowMultipleUsersRaw,
    FollowSpecificUserRaw,
    FollowersRaw,
    ListAllRaw,
    ListOfFollowedUsersRaw,
    ListOfFollowingUsersRaw,
    StopFollowingUserRaw,
    UserRaw,
    User0Raw,
    UsersRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
