# coding: utf-8

"""
    Vimeo API

    Build something great. Vimeo's API supports flexible, high-quality video integration with your custom apps.

    The version of the OpenAPI document: 3.4
    Created by: https://developer.vimeo.com/help
"""

from vimeo_python_sdk.paths.videos_video_id_versions.post import AddVideoVersion
from vimeo_python_sdk.paths.videos_video_id_versions_version_id.delete import DeleteVideoVersion
from vimeo_python_sdk.paths.videos_video_id_versions_version_id.patch import EditVideoVersion
from vimeo_python_sdk.paths.channels_channel_id_videos_video_id_versions.get import GetAllVideoVersions
from vimeo_python_sdk.paths.videos_video_id_versions.get import GetAllVideoVersions0
from vimeo_python_sdk.paths.videos_video_id_versions_version_id.get import GetSpecificVersion
from vimeo_python_sdk.apis.tags.videos_versions_api_raw import VideosVersionsApiRaw


class VideosVersionsApi(
    AddVideoVersion,
    DeleteVideoVersion,
    EditVideoVersion,
    GetAllVideoVersions,
    GetAllVideoVersions0,
    GetSpecificVersion,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: VideosVersionsApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = VideosVersionsApiRaw(api_client)
