# coding: utf-8

"""
    Vimeo API

    Build something great. Vimeo's API supports flexible, high-quality video integration with your custom apps.

    The version of the OpenAPI document: 3.4
    Created by: https://developer.vimeo.com/help
"""

from vimeo_python_sdk.paths.videos_video_id_tags.put import AddMultiple
from vimeo_python_sdk.paths.videos_video_id_tags_word.put import AddTagToVideo
from vimeo_python_sdk.paths.videos_video_id_tags_word.get import CheckTagVideo
from vimeo_python_sdk.paths.tags_word_videos.get import GetAllByTag
from vimeo_python_sdk.paths.videos_video_id_tags.get import GetVideoTags
from vimeo_python_sdk.paths.videos_video_id_tags_word.delete import RemoveTag
from vimeo_python_sdk.apis.tags.videos_tags_api_raw import VideosTagsApiRaw


class VideosTagsApi(
    AddMultiple,
    AddTagToVideo,
    CheckTagVideo,
    GetAllByTag,
    GetVideoTags,
    RemoveTag,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: VideosTagsApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = VideosTagsApiRaw(api_client)
