# coding: utf-8

"""
    Vimeo API

    Build something great. Vimeo's API supports flexible, high-quality video integration with your custom apps.

    The version of the OpenAPI document: 3.4
    Created by: https://developer.vimeo.com/help
"""

from vimeo_python_sdk.paths.me_videos_video_id_m3u8_playback.get import GetPlaybackUrlRaw
from vimeo_python_sdk.paths.users_user_id_videos_video_id_m3u8_playback.get import GetPlaybackUrlForEventStreamRaw


class VideosLiveM3U8PlaybackApiRaw(
    GetPlaybackUrlRaw,
    GetPlaybackUrlForEventStreamRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
