# coding: utf-8

"""
    Vimeo API

    Build something great. Vimeo's API supports flexible, high-quality video integration with your custom apps.

    The version of the OpenAPI document: 3.4
    Created by: https://developer.vimeo.com/help
"""

from vimeo_python_sdk.paths.me_watchlater_video_id.put import AddVideoToQueueRaw
from vimeo_python_sdk.paths.users_user_id_watchlater_video_id.put import AddVideoToQueue0Raw
from vimeo_python_sdk.paths.me_watchlater_video_id.get import CheckVideoInQueueRaw
from vimeo_python_sdk.paths.users_user_id_watchlater_video_id.get import CheckVideoInQueue0Raw
from vimeo_python_sdk.paths.me_watchlater.get import GetVideosInQueueRaw
from vimeo_python_sdk.paths.users_user_id_watchlater.get import ListUserQueueVideosRaw
from vimeo_python_sdk.paths.me_watchlater_video_id.delete import RemoveVideoFromQueueRaw
from vimeo_python_sdk.paths.users_user_id_watchlater_video_id.delete import RemoveVideoFromQueue0Raw


class WatchLaterQueueEssentialsApiRaw(
    AddVideoToQueueRaw,
    AddVideoToQueue0Raw,
    CheckVideoInQueueRaw,
    CheckVideoInQueue0Raw,
    GetVideosInQueueRaw,
    ListUserQueueVideosRaw,
    RemoveVideoFromQueueRaw,
    RemoveVideoFromQueue0Raw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
