# coding: utf-8

"""
    Vimeo API

    Build something great. Vimeo's API supports flexible, high-quality video integration with your custom apps.

    The version of the OpenAPI document: 3.4
    Created by: https://developer.vimeo.com/help
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel

from vimeo_python_sdk.pydantic.segment_line import SegmentLine
from vimeo_python_sdk.pydantic.segment_words import SegmentWords

class Segment(BaseModel):
    # Whether the segment is autogenerated.
    autogenerated: bool = Field(alias='autogenerated')

    # The cue end timestamp in milliseconds from the start of the video.
    cue_end: typing.Union[int, float] = Field(alias='cue_end')

    # The cue start timestamp in milliseconds from the start of the video.
    cue_start: typing.Union[int, float] = Field(alias='cue_start')

    # Whether the segment is enabled.
    enabled: bool = Field(alias='enabled')

    # The segment identifier.
    id: str = Field(alias='id')

    # The type of caption that the segment originates from.  Option descriptions:  * `captions` - The segment originates from a captions file.  * `subtitles` - The segment originates from a captions and subtitles file. 
    kind: Literal["captions", "subtitles"] = Field(alias='kind')

    # The language of the segment.
    language: str = Field(alias='language')

    # The line data for the segment.
    lines: typing.List[SegmentLine] = Field(alias='lines')

    # The speaker identifier.
    speaker: str = Field(alias='speaker')

    # The relative URI of the text track that the segment comes from.
    text_track_uri: str = Field(alias='text_track_uri')

    # The word data for the segment.
    words: typing.List[SegmentWords] = Field(alias='words')

    # The canonical relative URI of the segment's video.
    video_uri: typing.Optional[str] = Field(None, alias='video_uri')
    class Config:
        arbitrary_types_allowed = True
