# coding: utf-8

"""
    Vimeo API

    Build something great. Vimeo's API supports flexible, high-quality video integration with your custom apps.

    The version of the OpenAPI document: 3.4
    Created by: https://developer.vimeo.com/help
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from vimeo_python_sdk import schemas  # noqa: F401


class EditVideoRequest(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        
        class properties:
            description = schemas.StrSchema
        
            @staticmethod
            def content_rating() -> typing.Type['EditVideoRequestContentRating']:
                return EditVideoRequestContentRating
            custom_url = schemas.StrSchema
        
            @staticmethod
            def embed() -> typing.Type['EditVideoRequestEmbed']:
                return EditVideoRequestEmbed
        
            @staticmethod
            def embed_domains() -> typing.Type['EditVideoRequestEmbedDomains']:
                return EditVideoRequestEmbedDomains
        
            @staticmethod
            def embed_domains_add() -> typing.Type['EditVideoRequestEmbedDomainsAdd']:
                return EditVideoRequestEmbedDomainsAdd
        
            @staticmethod
            def embed_domains_delete() -> typing.Type['EditVideoRequestEmbedDomainsDelete']:
                return EditVideoRequestEmbedDomainsDelete
            hide_from_vimeo = schemas.BoolSchema
            
            
            class license(
                schemas.EnumBase,
                schemas.StrSchema
            ):
            
            
                class MetaOapg:
                    enum_value_to_name = {
                        "by": "BY",
                        "by-nc": "BYNC",
                        "by-nc-nd": "BYNCND",
                        "by-nc-sa": "BYNCSA",
                        "by-nd": "BYND",
                        "by-sa": "BYSA",
                        "cc0": "CC0",
                    }
                
                @schemas.classproperty
                def BY(cls):
                    return cls("by")
                
                @schemas.classproperty
                def BYNC(cls):
                    return cls("by-nc")
                
                @schemas.classproperty
                def BYNCND(cls):
                    return cls("by-nc-nd")
                
                @schemas.classproperty
                def BYNCSA(cls):
                    return cls("by-nc-sa")
                
                @schemas.classproperty
                def BYND(cls):
                    return cls("by-nd")
                
                @schemas.classproperty
                def BYSA(cls):
                    return cls("by-sa")
                
                @schemas.classproperty
                def CC0(cls):
                    return cls("cc0")
            locale = schemas.StrSchema
            name = schemas.StrSchema
            password = schemas.StrSchema
        
            @staticmethod
            def privacy() -> typing.Type['EditVideoRequestPrivacy']:
                return EditVideoRequestPrivacy
        
            @staticmethod
            def review_page() -> typing.Type['EditVideoRequestReviewPage']:
                return EditVideoRequestReviewPage
        
            @staticmethod
            def spatial() -> typing.Type['EditVideoRequestSpatial']:
                return EditVideoRequestSpatial
            __annotations__ = {
                "description": description,
                "content_rating": content_rating,
                "custom_url": custom_url,
                "embed": embed,
                "embed_domains": embed_domains,
                "embed_domains_add": embed_domains_add,
                "embed_domains_delete": embed_domains_delete,
                "hide_from_vimeo": hide_from_vimeo,
                "license": license,
                "locale": locale,
                "name": name,
                "password": password,
                "privacy": privacy,
                "review_page": review_page,
                "spatial": spatial,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["description"]) -> MetaOapg.properties.description: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["content_rating"]) -> 'EditVideoRequestContentRating': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["custom_url"]) -> MetaOapg.properties.custom_url: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["embed"]) -> 'EditVideoRequestEmbed': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["embed_domains"]) -> 'EditVideoRequestEmbedDomains': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["embed_domains_add"]) -> 'EditVideoRequestEmbedDomainsAdd': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["embed_domains_delete"]) -> 'EditVideoRequestEmbedDomainsDelete': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["hide_from_vimeo"]) -> MetaOapg.properties.hide_from_vimeo: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["license"]) -> MetaOapg.properties.license: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["locale"]) -> MetaOapg.properties.locale: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["name"]) -> MetaOapg.properties.name: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["password"]) -> MetaOapg.properties.password: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["privacy"]) -> 'EditVideoRequestPrivacy': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["review_page"]) -> 'EditVideoRequestReviewPage': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["spatial"]) -> 'EditVideoRequestSpatial': ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["description", "content_rating", "custom_url", "embed", "embed_domains", "embed_domains_add", "embed_domains_delete", "hide_from_vimeo", "license", "locale", "name", "password", "privacy", "review_page", "spatial", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["description"]) -> typing.Union[MetaOapg.properties.description, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["content_rating"]) -> typing.Union['EditVideoRequestContentRating', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["custom_url"]) -> typing.Union[MetaOapg.properties.custom_url, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["embed"]) -> typing.Union['EditVideoRequestEmbed', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["embed_domains"]) -> typing.Union['EditVideoRequestEmbedDomains', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["embed_domains_add"]) -> typing.Union['EditVideoRequestEmbedDomainsAdd', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["embed_domains_delete"]) -> typing.Union['EditVideoRequestEmbedDomainsDelete', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["hide_from_vimeo"]) -> typing.Union[MetaOapg.properties.hide_from_vimeo, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["license"]) -> typing.Union[MetaOapg.properties.license, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["locale"]) -> typing.Union[MetaOapg.properties.locale, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["name"]) -> typing.Union[MetaOapg.properties.name, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["password"]) -> typing.Union[MetaOapg.properties.password, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["privacy"]) -> typing.Union['EditVideoRequestPrivacy', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["review_page"]) -> typing.Union['EditVideoRequestReviewPage', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["spatial"]) -> typing.Union['EditVideoRequestSpatial', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["description", "content_rating", "custom_url", "embed", "embed_domains", "embed_domains_add", "embed_domains_delete", "hide_from_vimeo", "license", "locale", "name", "password", "privacy", "review_page", "spatial", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        description: typing.Union[MetaOapg.properties.description, str, schemas.Unset] = schemas.unset,
        content_rating: typing.Union['EditVideoRequestContentRating', schemas.Unset] = schemas.unset,
        custom_url: typing.Union[MetaOapg.properties.custom_url, str, schemas.Unset] = schemas.unset,
        embed: typing.Union['EditVideoRequestEmbed', schemas.Unset] = schemas.unset,
        embed_domains: typing.Union['EditVideoRequestEmbedDomains', schemas.Unset] = schemas.unset,
        embed_domains_add: typing.Union['EditVideoRequestEmbedDomainsAdd', schemas.Unset] = schemas.unset,
        embed_domains_delete: typing.Union['EditVideoRequestEmbedDomainsDelete', schemas.Unset] = schemas.unset,
        hide_from_vimeo: typing.Union[MetaOapg.properties.hide_from_vimeo, bool, schemas.Unset] = schemas.unset,
        license: typing.Union[MetaOapg.properties.license, str, schemas.Unset] = schemas.unset,
        locale: typing.Union[MetaOapg.properties.locale, str, schemas.Unset] = schemas.unset,
        name: typing.Union[MetaOapg.properties.name, str, schemas.Unset] = schemas.unset,
        password: typing.Union[MetaOapg.properties.password, str, schemas.Unset] = schemas.unset,
        privacy: typing.Union['EditVideoRequestPrivacy', schemas.Unset] = schemas.unset,
        review_page: typing.Union['EditVideoRequestReviewPage', schemas.Unset] = schemas.unset,
        spatial: typing.Union['EditVideoRequestSpatial', schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'EditVideoRequest':
        return super().__new__(
            cls,
            *args,
            description=description,
            content_rating=content_rating,
            custom_url=custom_url,
            embed=embed,
            embed_domains=embed_domains,
            embed_domains_add=embed_domains_add,
            embed_domains_delete=embed_domains_delete,
            hide_from_vimeo=hide_from_vimeo,
            license=license,
            locale=locale,
            name=name,
            password=password,
            privacy=privacy,
            review_page=review_page,
            spatial=spatial,
            _configuration=_configuration,
            **kwargs,
        )

from vimeo_python_sdk.model.edit_video_request_content_rating import EditVideoRequestContentRating
from vimeo_python_sdk.model.edit_video_request_embed import EditVideoRequestEmbed
from vimeo_python_sdk.model.edit_video_request_embed_domains import EditVideoRequestEmbedDomains
from vimeo_python_sdk.model.edit_video_request_embed_domains_add import EditVideoRequestEmbedDomainsAdd
from vimeo_python_sdk.model.edit_video_request_embed_domains_delete import EditVideoRequestEmbedDomainsDelete
from vimeo_python_sdk.model.edit_video_request_privacy import EditVideoRequestPrivacy
from vimeo_python_sdk.model.edit_video_request_review_page import EditVideoRequestReviewPage
from vimeo_python_sdk.model.edit_video_request_spatial import EditVideoRequestSpatial
