# coding: utf-8

"""
    Vimeo API

    Build something great. Vimeo's API supports flexible, high-quality video integration with your custom apps.

    The version of the OpenAPI document: 3.4
    Created by: https://developer.vimeo.com/help
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from vimeo_python_sdk import schemas  # noqa: F401


class EmailCaptureFormHiddenFieldsItemFieldMetadata(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)

    The metadata object that is associated with the field in the form.
    """


    class MetaOapg:
        required = {
            "options",
        }
        
        class properties:
        
            @staticmethod
            def options() -> typing.Type['EmailCaptureFormHiddenFieldsItemFieldMetadataOptions']:
                return EmailCaptureFormHiddenFieldsItemFieldMetadataOptions
            __annotations__ = {
                "options": options,
            }
    
    options: 'EmailCaptureFormHiddenFieldsItemFieldMetadataOptions'
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["options"]) -> 'EmailCaptureFormHiddenFieldsItemFieldMetadataOptions': ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["options", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["options"]) -> 'EmailCaptureFormHiddenFieldsItemFieldMetadataOptions': ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["options", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        options: 'EmailCaptureFormHiddenFieldsItemFieldMetadataOptions',
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'EmailCaptureFormHiddenFieldsItemFieldMetadata':
        return super().__new__(
            cls,
            *args,
            options=options,
            _configuration=_configuration,
            **kwargs,
        )

from vimeo_python_sdk.model.email_capture_form_hidden_fields_item_field_metadata_options import EmailCaptureFormHiddenFieldsItemFieldMetadataOptions
