# coding: utf-8

"""
    Vimeo API

    Build something great. Vimeo's API supports flexible, high-quality video integration with your custom apps.

    The version of the OpenAPI document: 3.4
    Created by: https://developer.vimeo.com/help
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from vimeo_python_sdk import schemas  # noqa: F401


class EmailCaptureFormCustomFieldsItemFieldMetadataOptionsItem(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        required = {
            "option_label",
            "option_position",
        }
        
        class properties:
            option_label = schemas.StrSchema
            option_position = schemas.NumberSchema
            __annotations__ = {
                "option_label": option_label,
                "option_position": option_position,
            }
    
    option_label: MetaOapg.properties.option_label
    option_position: MetaOapg.properties.option_position
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["option_label"]) -> MetaOapg.properties.option_label: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["option_position"]) -> MetaOapg.properties.option_position: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["option_label", "option_position", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["option_label"]) -> MetaOapg.properties.option_label: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["option_position"]) -> MetaOapg.properties.option_position: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["option_label", "option_position", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        option_label: typing.Union[MetaOapg.properties.option_label, str, ],
        option_position: typing.Union[MetaOapg.properties.option_position, decimal.Decimal, int, float, ],
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'EmailCaptureFormCustomFieldsItemFieldMetadataOptionsItem':
        return super().__new__(
            cls,
            *args,
            option_label=option_label,
            option_position=option_position,
            _configuration=_configuration,
            **kwargs,
        )
