# coding: utf-8

"""
    Vimeo API

    Build something great. Vimeo's API supports flexible, high-quality video integration with your custom apps.

    The version of the OpenAPI document: 3.4
    Created by: https://developer.vimeo.com/help
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from vimeo_python_sdk import schemas  # noqa: F401


class LiveEmbedPrivacyEmbedEventOnDomainsRequest2(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        
        class properties:
        
            @staticmethod
            def allowed_domains() -> typing.Type['LiveEmbedPrivacyEmbedEventOnDomainsRequest2AllowedDomains']:
                return LiveEmbedPrivacyEmbedEventOnDomainsRequest2AllowedDomains
            __annotations__ = {
                "allowed_domains": allowed_domains,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["allowed_domains"]) -> 'LiveEmbedPrivacyEmbedEventOnDomainsRequest2AllowedDomains': ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["allowed_domains", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["allowed_domains"]) -> typing.Union['LiveEmbedPrivacyEmbedEventOnDomainsRequest2AllowedDomains', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["allowed_domains", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        allowed_domains: typing.Union['LiveEmbedPrivacyEmbedEventOnDomainsRequest2AllowedDomains', schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'LiveEmbedPrivacyEmbedEventOnDomainsRequest2':
        return super().__new__(
            cls,
            *args,
            allowed_domains=allowed_domains,
            _configuration=_configuration,
            **kwargs,
        )

from vimeo_python_sdk.model.live_embed_privacy_embed_event_on_domains_request2_allowed_domains import LiveEmbedPrivacyEmbedEventOnDomainsRequest2AllowedDomains
