# coding: utf-8

"""
    Vimeo API

    Build something great. Vimeo's API supports flexible, high-quality video integration with your custom apps.

    The version of the OpenAPI document: 3.4
    Created by: https://developer.vimeo.com/help
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from vimeo_python_sdk import schemas  # noqa: F401


class OnDemandPageEpisodes(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)

    Information about the On Demand page's episodes, if the page is for a series.
    """


    class MetaOapg:
        required = {
            "buy",
            "rent",
        }
        
        class properties:
        
            @staticmethod
            def buy() -> typing.Type['OnDemandPageEpisodesBuy']:
                return OnDemandPageEpisodesBuy
        
            @staticmethod
            def rent() -> typing.Type['OnDemandPageEpisodesRent']:
                return OnDemandPageEpisodesRent
            __annotations__ = {
                "buy": buy,
                "rent": rent,
            }
    
    buy: 'OnDemandPageEpisodesBuy'
    rent: 'OnDemandPageEpisodesRent'
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["buy"]) -> 'OnDemandPageEpisodesBuy': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["rent"]) -> 'OnDemandPageEpisodesRent': ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["buy", "rent", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["buy"]) -> 'OnDemandPageEpisodesBuy': ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["rent"]) -> 'OnDemandPageEpisodesRent': ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["buy", "rent", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        buy: 'OnDemandPageEpisodesBuy',
        rent: 'OnDemandPageEpisodesRent',
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'OnDemandPageEpisodes':
        return super().__new__(
            cls,
            *args,
            buy=buy,
            rent=rent,
            _configuration=_configuration,
            **kwargs,
        )

from vimeo_python_sdk.model.on_demand_page_episodes_buy import OnDemandPageEpisodesBuy
from vimeo_python_sdk.model.on_demand_page_episodes_rent import OnDemandPageEpisodesRent
