# coding: utf-8

"""
    Vimeo API

    Build something great. Vimeo's API supports flexible, high-quality video integration with your custom apps.

    The version of the OpenAPI document: 3.4
    Created by: https://developer.vimeo.com/help
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from vimeo_python_sdk import schemas  # noqa: F401


class SubscriptionPlansPromotionPrice(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)

    The price map of the promotion.
    """


    class MetaOapg:
        
        class properties:
            annual = schemas.NumberSchema
            annual_monthly = schemas.NumberSchema
            monthly = schemas.NumberSchema
            __annotations__ = {
                "annual": annual,
                "annual_monthly": annual_monthly,
                "monthly": monthly,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["annual"]) -> MetaOapg.properties.annual: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["annual_monthly"]) -> MetaOapg.properties.annual_monthly: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["monthly"]) -> MetaOapg.properties.monthly: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["annual", "annual_monthly", "monthly", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["annual"]) -> typing.Union[MetaOapg.properties.annual, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["annual_monthly"]) -> typing.Union[MetaOapg.properties.annual_monthly, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["monthly"]) -> typing.Union[MetaOapg.properties.monthly, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["annual", "annual_monthly", "monthly", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        annual: typing.Union[MetaOapg.properties.annual, decimal.Decimal, int, float, schemas.Unset] = schemas.unset,
        annual_monthly: typing.Union[MetaOapg.properties.annual_monthly, decimal.Decimal, int, float, schemas.Unset] = schemas.unset,
        monthly: typing.Union[MetaOapg.properties.monthly, decimal.Decimal, int, float, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'SubscriptionPlansPromotionPrice':
        return super().__new__(
            cls,
            *args,
            annual=annual,
            annual_monthly=annual_monthly,
            monthly=monthly,
            _configuration=_configuration,
            **kwargs,
        )
