# coding: utf-8

"""
    Vimeo API

    Build something great. Vimeo's API supports flexible, high-quality video integration with your custom apps.

    The version of the OpenAPI document: 3.4
    Created by: https://developer.vimeo.com/help
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from vimeo_python_sdk import schemas  # noqa: F401


class TeamRoleApplicablePermissionPolicies(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)

    The applicable permission policies for the role.
    """


    class MetaOapg:
        
        class properties:
        
            @staticmethod
            def folder() -> typing.Type['TeamRoleApplicablePermissionPoliciesFolder']:
                return TeamRoleApplicablePermissionPoliciesFolder
        
            @staticmethod
            def regional_delivery() -> typing.Type['TeamRoleApplicablePermissionPoliciesRegionalDelivery']:
                return TeamRoleApplicablePermissionPoliciesRegionalDelivery
        
            @staticmethod
            def video() -> typing.Type['TeamRoleApplicablePermissionPoliciesVideo']:
                return TeamRoleApplicablePermissionPoliciesVideo
            __annotations__ = {
                "folder": folder,
                "regional_delivery": regional_delivery,
                "video": video,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["folder"]) -> 'TeamRoleApplicablePermissionPoliciesFolder': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["regional_delivery"]) -> 'TeamRoleApplicablePermissionPoliciesRegionalDelivery': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["video"]) -> 'TeamRoleApplicablePermissionPoliciesVideo': ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["folder", "regional_delivery", "video", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["folder"]) -> typing.Union['TeamRoleApplicablePermissionPoliciesFolder', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["regional_delivery"]) -> typing.Union['TeamRoleApplicablePermissionPoliciesRegionalDelivery', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["video"]) -> typing.Union['TeamRoleApplicablePermissionPoliciesVideo', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["folder", "regional_delivery", "video", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        folder: typing.Union['TeamRoleApplicablePermissionPoliciesFolder', schemas.Unset] = schemas.unset,
        regional_delivery: typing.Union['TeamRoleApplicablePermissionPoliciesRegionalDelivery', schemas.Unset] = schemas.unset,
        video: typing.Union['TeamRoleApplicablePermissionPoliciesVideo', schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'TeamRoleApplicablePermissionPolicies':
        return super().__new__(
            cls,
            *args,
            folder=folder,
            regional_delivery=regional_delivery,
            video=video,
            _configuration=_configuration,
            **kwargs,
        )

from vimeo_python_sdk.model.team_role_applicable_permission_policies_folder import TeamRoleApplicablePermissionPoliciesFolder
from vimeo_python_sdk.model.team_role_applicable_permission_policies_regional_delivery import TeamRoleApplicablePermissionPoliciesRegionalDelivery
from vimeo_python_sdk.model.team_role_applicable_permission_policies_video import TeamRoleApplicablePermissionPoliciesVideo
