# coding: utf-8

"""
    Vimeo API

    Build something great. Vimeo's API supports flexible, high-quality video integration with your custom apps.

    The version of the OpenAPI document: 3.4
    Created by: https://developer.vimeo.com/help
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from vimeo_python_sdk import schemas  # noqa: F401


class TeamMembershipMetadataConnections(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)

    A list of resource URIs related to the user.
    """


    class MetaOapg:
        required = {
            "owner",
            "personal_team_folder",
        }
        
        class properties:
        
            @staticmethod
            def owner() -> typing.Type['TeamMembershipMetadataConnectionsOwner']:
                return TeamMembershipMetadataConnectionsOwner
        
            @staticmethod
            def personal_team_folder() -> typing.Type['TeamMembershipMetadataConnectionsPersonalTeamFolder']:
                return TeamMembershipMetadataConnectionsPersonalTeamFolder
            __annotations__ = {
                "owner": owner,
                "personal_team_folder": personal_team_folder,
            }
    
    owner: 'TeamMembershipMetadataConnectionsOwner'
    personal_team_folder: 'TeamMembershipMetadataConnectionsPersonalTeamFolder'
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["owner"]) -> 'TeamMembershipMetadataConnectionsOwner': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["personal_team_folder"]) -> 'TeamMembershipMetadataConnectionsPersonalTeamFolder': ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["owner", "personal_team_folder", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["owner"]) -> 'TeamMembershipMetadataConnectionsOwner': ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["personal_team_folder"]) -> 'TeamMembershipMetadataConnectionsPersonalTeamFolder': ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["owner", "personal_team_folder", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        owner: 'TeamMembershipMetadataConnectionsOwner',
        personal_team_folder: 'TeamMembershipMetadataConnectionsPersonalTeamFolder',
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'TeamMembershipMetadataConnections':
        return super().__new__(
            cls,
            *args,
            owner=owner,
            personal_team_folder=personal_team_folder,
            _configuration=_configuration,
            **kwargs,
        )

from vimeo_python_sdk.model.team_membership_metadata_connections_owner import TeamMembershipMetadataConnectionsOwner
from vimeo_python_sdk.model.team_membership_metadata_connections_personal_team_folder import TeamMembershipMetadataConnectionsPersonalTeamFolder
