# coding: utf-8

"""
    Vimeo API

    Build something great. Vimeo's API supports flexible, high-quality video integration with your custom apps.

    The version of the OpenAPI document: 3.4
    Created by: https://developer.vimeo.com/help
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from vimeo_python_sdk import schemas  # noqa: F401


class UserUploadQuotaSpace(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)

    Information about the authenticated user's upload space remaining for the current period.
    """


    class MetaOapg:
        required = {
            "unit",
            "max",
            "used",
            "free",
            "showing",
        }
        
        class properties:
            free = schemas.NumberSchema
            
            
            class max(
                schemas.NumberBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneDecimalMixin
            ):
            
            
                def __new__(
                    cls,
                    *args: typing.Union[None, decimal.Decimal, int, float, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'max':
                    return super().__new__(
                        cls,
                        *args,
                        _configuration=_configuration,
                    )
            
            
            class showing(
                schemas.EnumBase,
                schemas.StrSchema
            ):
            
            
                class MetaOapg:
                    enum_value_to_name = {
                        "lifetime": "LIFETIME",
                        "periodic": "PERIODIC",
                    }
                
                @schemas.classproperty
                def LIFETIME(cls):
                    return cls("lifetime")
                
                @schemas.classproperty
                def PERIODIC(cls):
                    return cls("periodic")
            
            
            class unit(
                schemas.EnumBase,
                schemas.StrBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneStrMixin
            ):
            
            
                class MetaOapg:
                    enum_value_to_name = {
                        "video_count": "COUNT",
                        "video_size": "SIZE",
                    }
                
                @schemas.classproperty
                def COUNT(cls):
                    return cls("video_count")
                
                @schemas.classproperty
                def SIZE(cls):
                    return cls("video_size")
            
            
                def __new__(
                    cls,
                    *args: typing.Union[None, str, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'unit':
                    return super().__new__(
                        cls,
                        *args,
                        _configuration=_configuration,
                    )
            used = schemas.NumberSchema
            __annotations__ = {
                "free": free,
                "max": max,
                "showing": showing,
                "unit": unit,
                "used": used,
            }
    
    unit: MetaOapg.properties.unit
    max: MetaOapg.properties.max
    used: MetaOapg.properties.used
    free: MetaOapg.properties.free
    showing: MetaOapg.properties.showing
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["free"]) -> MetaOapg.properties.free: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["max"]) -> MetaOapg.properties.max: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["showing"]) -> MetaOapg.properties.showing: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["unit"]) -> MetaOapg.properties.unit: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["used"]) -> MetaOapg.properties.used: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["free", "max", "showing", "unit", "used", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["free"]) -> MetaOapg.properties.free: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["max"]) -> MetaOapg.properties.max: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["showing"]) -> MetaOapg.properties.showing: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["unit"]) -> MetaOapg.properties.unit: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["used"]) -> MetaOapg.properties.used: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["free", "max", "showing", "unit", "used", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        unit: typing.Union[MetaOapg.properties.unit, None, str, ],
        max: typing.Union[MetaOapg.properties.max, None, decimal.Decimal, int, float, ],
        used: typing.Union[MetaOapg.properties.used, decimal.Decimal, int, float, ],
        free: typing.Union[MetaOapg.properties.free, decimal.Decimal, int, float, ],
        showing: typing.Union[MetaOapg.properties.showing, str, ],
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'UserUploadQuotaSpace':
        return super().__new__(
            cls,
            *args,
            unit=unit,
            max=max,
            used=used,
            free=free,
            showing=showing,
            _configuration=_configuration,
            **kwargs,
        )
