# coding: utf-8

"""
    Vimeo API

    Build something great. Vimeo's API supports flexible, high-quality video integration with your custom apps.

    The version of the OpenAPI document: 3.4
    Created by: https://developer.vimeo.com/help
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from vimeo_python_sdk import schemas  # noqa: F401


class UsersEssentialsEditVimeoAccountRequest(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        
        class properties:
            bio = schemas.StrSchema
        
            @staticmethod
            def content_filter() -> typing.Type['UsersEssentialsEditVimeoAccountRequestContentFilter']:
                return UsersEssentialsEditVimeoAccountRequestContentFilter
            
            
            class gender(
                schemas.EnumBase,
                schemas.StrSchema
            ):
                
                @schemas.classproperty
                def F(cls):
                    return cls("f")
                
                @schemas.classproperty
                def M(cls):
                    return cls("m")
                
                @schemas.classproperty
                def N(cls):
                    return cls("n")
                
                @schemas.classproperty
                def O(cls):
                    return cls("o")
            link = schemas.StrSchema
            location = schemas.StrSchema
            name = schemas.StrSchema
            password = schemas.StrSchema
        
            @staticmethod
            def videos() -> typing.Type['UsersEssentialsEditVimeoAccountRequestVideos']:
                return UsersEssentialsEditVimeoAccountRequestVideos
            __annotations__ = {
                "bio": bio,
                "content_filter": content_filter,
                "gender": gender,
                "link": link,
                "location": location,
                "name": name,
                "password": password,
                "videos": videos,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["bio"]) -> MetaOapg.properties.bio: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["content_filter"]) -> 'UsersEssentialsEditVimeoAccountRequestContentFilter': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["gender"]) -> MetaOapg.properties.gender: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["link"]) -> MetaOapg.properties.link: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["location"]) -> MetaOapg.properties.location: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["name"]) -> MetaOapg.properties.name: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["password"]) -> MetaOapg.properties.password: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["videos"]) -> 'UsersEssentialsEditVimeoAccountRequestVideos': ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["bio", "content_filter", "gender", "link", "location", "name", "password", "videos", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["bio"]) -> typing.Union[MetaOapg.properties.bio, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["content_filter"]) -> typing.Union['UsersEssentialsEditVimeoAccountRequestContentFilter', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["gender"]) -> typing.Union[MetaOapg.properties.gender, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["link"]) -> typing.Union[MetaOapg.properties.link, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["location"]) -> typing.Union[MetaOapg.properties.location, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["name"]) -> typing.Union[MetaOapg.properties.name, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["password"]) -> typing.Union[MetaOapg.properties.password, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["videos"]) -> typing.Union['UsersEssentialsEditVimeoAccountRequestVideos', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["bio", "content_filter", "gender", "link", "location", "name", "password", "videos", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        bio: typing.Union[MetaOapg.properties.bio, str, schemas.Unset] = schemas.unset,
        content_filter: typing.Union['UsersEssentialsEditVimeoAccountRequestContentFilter', schemas.Unset] = schemas.unset,
        gender: typing.Union[MetaOapg.properties.gender, str, schemas.Unset] = schemas.unset,
        link: typing.Union[MetaOapg.properties.link, str, schemas.Unset] = schemas.unset,
        location: typing.Union[MetaOapg.properties.location, str, schemas.Unset] = schemas.unset,
        name: typing.Union[MetaOapg.properties.name, str, schemas.Unset] = schemas.unset,
        password: typing.Union[MetaOapg.properties.password, str, schemas.Unset] = schemas.unset,
        videos: typing.Union['UsersEssentialsEditVimeoAccountRequestVideos', schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'UsersEssentialsEditVimeoAccountRequest':
        return super().__new__(
            cls,
            *args,
            bio=bio,
            content_filter=content_filter,
            gender=gender,
            link=link,
            location=location,
            name=name,
            password=password,
            videos=videos,
            _configuration=_configuration,
            **kwargs,
        )

from vimeo_python_sdk.model.users_essentials_edit_vimeo_account_request_content_filter import UsersEssentialsEditVimeoAccountRequestContentFilter
from vimeo_python_sdk.model.users_essentials_edit_vimeo_account_request_videos import UsersEssentialsEditVimeoAccountRequestVideos
