# coding: utf-8

"""
    Vimeo API

    Build something great. Vimeo's API supports flexible, high-quality video integration with your custom apps.

    The version of the OpenAPI document: 3.4
    Created by: https://developer.vimeo.com/help
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from vimeo_python_sdk import schemas  # noqa: F401


class VideosUploadsBeginVideoUploadProcessRequest(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        required = {
            "upload",
        }
        
        class properties:
        
            @staticmethod
            def upload() -> typing.Type['VideosUploadsBeginVideoUploadProcessRequestUpload']:
                return VideosUploadsBeginVideoUploadProcessRequestUpload
            description = schemas.StrSchema
        
            @staticmethod
            def content_rating() -> typing.Type['VideosUploadsBeginVideoUploadProcessRequestContentRating']:
                return VideosUploadsBeginVideoUploadProcessRequestContentRating
        
            @staticmethod
            def embed() -> typing.Type['VideosUploadsBeginVideoUploadProcessRequestEmbed']:
                return VideosUploadsBeginVideoUploadProcessRequestEmbed
        
            @staticmethod
            def embed_domains() -> typing.Type['VideosUploadsBeginVideoUploadProcessRequestEmbedDomains']:
                return VideosUploadsBeginVideoUploadProcessRequestEmbedDomains
            folder_uri = schemas.StrSchema
            hide_from_vimeo = schemas.BoolSchema
            
            
            class license(
                schemas.EnumBase,
                schemas.StrSchema
            ):
            
            
                class MetaOapg:
                    enum_value_to_name = {
                        "by": "BY",
                        "by-nc": "BYNC",
                        "by-nc-nd": "BYNCND",
                        "by-nc-sa": "BYNCSA",
                        "by-nd": "BYND",
                        "by-sa": "BYSA",
                        "cc0": "CC0",
                    }
                
                @schemas.classproperty
                def BY(cls):
                    return cls("by")
                
                @schemas.classproperty
                def BYNC(cls):
                    return cls("by-nc")
                
                @schemas.classproperty
                def BYNCND(cls):
                    return cls("by-nc-nd")
                
                @schemas.classproperty
                def BYNCSA(cls):
                    return cls("by-nc-sa")
                
                @schemas.classproperty
                def BYND(cls):
                    return cls("by-nd")
                
                @schemas.classproperty
                def BYSA(cls):
                    return cls("by-sa")
                
                @schemas.classproperty
                def CC0(cls):
                    return cls("cc0")
            locale = schemas.StrSchema
            name = schemas.StrSchema
            password = schemas.StrSchema
        
            @staticmethod
            def privacy() -> typing.Type['VideosUploadsBeginVideoUploadProcessRequestPrivacy']:
                return VideosUploadsBeginVideoUploadProcessRequestPrivacy
        
            @staticmethod
            def review_page() -> typing.Type['VideosUploadsBeginVideoUploadProcessRequestReviewPage']:
                return VideosUploadsBeginVideoUploadProcessRequestReviewPage
        
            @staticmethod
            def spatial() -> typing.Type['VideosUploadsBeginVideoUploadProcessRequestSpatial']:
                return VideosUploadsBeginVideoUploadProcessRequestSpatial
            __annotations__ = {
                "upload": upload,
                "description": description,
                "content_rating": content_rating,
                "embed": embed,
                "embed_domains": embed_domains,
                "folder_uri": folder_uri,
                "hide_from_vimeo": hide_from_vimeo,
                "license": license,
                "locale": locale,
                "name": name,
                "password": password,
                "privacy": privacy,
                "review_page": review_page,
                "spatial": spatial,
            }
    
    upload: 'VideosUploadsBeginVideoUploadProcessRequestUpload'
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["upload"]) -> 'VideosUploadsBeginVideoUploadProcessRequestUpload': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["description"]) -> MetaOapg.properties.description: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["content_rating"]) -> 'VideosUploadsBeginVideoUploadProcessRequestContentRating': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["embed"]) -> 'VideosUploadsBeginVideoUploadProcessRequestEmbed': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["embed_domains"]) -> 'VideosUploadsBeginVideoUploadProcessRequestEmbedDomains': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["folder_uri"]) -> MetaOapg.properties.folder_uri: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["hide_from_vimeo"]) -> MetaOapg.properties.hide_from_vimeo: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["license"]) -> MetaOapg.properties.license: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["locale"]) -> MetaOapg.properties.locale: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["name"]) -> MetaOapg.properties.name: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["password"]) -> MetaOapg.properties.password: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["privacy"]) -> 'VideosUploadsBeginVideoUploadProcessRequestPrivacy': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["review_page"]) -> 'VideosUploadsBeginVideoUploadProcessRequestReviewPage': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["spatial"]) -> 'VideosUploadsBeginVideoUploadProcessRequestSpatial': ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["upload", "description", "content_rating", "embed", "embed_domains", "folder_uri", "hide_from_vimeo", "license", "locale", "name", "password", "privacy", "review_page", "spatial", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["upload"]) -> 'VideosUploadsBeginVideoUploadProcessRequestUpload': ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["description"]) -> typing.Union[MetaOapg.properties.description, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["content_rating"]) -> typing.Union['VideosUploadsBeginVideoUploadProcessRequestContentRating', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["embed"]) -> typing.Union['VideosUploadsBeginVideoUploadProcessRequestEmbed', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["embed_domains"]) -> typing.Union['VideosUploadsBeginVideoUploadProcessRequestEmbedDomains', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["folder_uri"]) -> typing.Union[MetaOapg.properties.folder_uri, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["hide_from_vimeo"]) -> typing.Union[MetaOapg.properties.hide_from_vimeo, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["license"]) -> typing.Union[MetaOapg.properties.license, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["locale"]) -> typing.Union[MetaOapg.properties.locale, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["name"]) -> typing.Union[MetaOapg.properties.name, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["password"]) -> typing.Union[MetaOapg.properties.password, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["privacy"]) -> typing.Union['VideosUploadsBeginVideoUploadProcessRequestPrivacy', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["review_page"]) -> typing.Union['VideosUploadsBeginVideoUploadProcessRequestReviewPage', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["spatial"]) -> typing.Union['VideosUploadsBeginVideoUploadProcessRequestSpatial', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["upload", "description", "content_rating", "embed", "embed_domains", "folder_uri", "hide_from_vimeo", "license", "locale", "name", "password", "privacy", "review_page", "spatial", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        upload: 'VideosUploadsBeginVideoUploadProcessRequestUpload',
        description: typing.Union[MetaOapg.properties.description, str, schemas.Unset] = schemas.unset,
        content_rating: typing.Union['VideosUploadsBeginVideoUploadProcessRequestContentRating', schemas.Unset] = schemas.unset,
        embed: typing.Union['VideosUploadsBeginVideoUploadProcessRequestEmbed', schemas.Unset] = schemas.unset,
        embed_domains: typing.Union['VideosUploadsBeginVideoUploadProcessRequestEmbedDomains', schemas.Unset] = schemas.unset,
        folder_uri: typing.Union[MetaOapg.properties.folder_uri, str, schemas.Unset] = schemas.unset,
        hide_from_vimeo: typing.Union[MetaOapg.properties.hide_from_vimeo, bool, schemas.Unset] = schemas.unset,
        license: typing.Union[MetaOapg.properties.license, str, schemas.Unset] = schemas.unset,
        locale: typing.Union[MetaOapg.properties.locale, str, schemas.Unset] = schemas.unset,
        name: typing.Union[MetaOapg.properties.name, str, schemas.Unset] = schemas.unset,
        password: typing.Union[MetaOapg.properties.password, str, schemas.Unset] = schemas.unset,
        privacy: typing.Union['VideosUploadsBeginVideoUploadProcessRequestPrivacy', schemas.Unset] = schemas.unset,
        review_page: typing.Union['VideosUploadsBeginVideoUploadProcessRequestReviewPage', schemas.Unset] = schemas.unset,
        spatial: typing.Union['VideosUploadsBeginVideoUploadProcessRequestSpatial', schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'VideosUploadsBeginVideoUploadProcessRequest':
        return super().__new__(
            cls,
            *args,
            upload=upload,
            description=description,
            content_rating=content_rating,
            embed=embed,
            embed_domains=embed_domains,
            folder_uri=folder_uri,
            hide_from_vimeo=hide_from_vimeo,
            license=license,
            locale=locale,
            name=name,
            password=password,
            privacy=privacy,
            review_page=review_page,
            spatial=spatial,
            _configuration=_configuration,
            **kwargs,
        )

from vimeo_python_sdk.model.videos_uploads_begin_video_upload_process_request_content_rating import VideosUploadsBeginVideoUploadProcessRequestContentRating
from vimeo_python_sdk.model.videos_uploads_begin_video_upload_process_request_embed import VideosUploadsBeginVideoUploadProcessRequestEmbed
from vimeo_python_sdk.model.videos_uploads_begin_video_upload_process_request_embed_domains import VideosUploadsBeginVideoUploadProcessRequestEmbedDomains
from vimeo_python_sdk.model.videos_uploads_begin_video_upload_process_request_privacy import VideosUploadsBeginVideoUploadProcessRequestPrivacy
from vimeo_python_sdk.model.videos_uploads_begin_video_upload_process_request_review_page import VideosUploadsBeginVideoUploadProcessRequestReviewPage
from vimeo_python_sdk.model.videos_uploads_begin_video_upload_process_request_spatial import VideosUploadsBeginVideoUploadProcessRequestSpatial
from vimeo_python_sdk.model.videos_uploads_begin_video_upload_process_request_upload import VideosUploadsBeginVideoUploadProcessRequestUpload
