# coding: utf-8

"""
    Vimeo API

    Build something great. Vimeo's API supports flexible, high-quality video integration with your custom apps.

    The version of the OpenAPI document: 3.4
    Created by: https://developer.vimeo.com/help
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from vimeo_python_sdk import schemas  # noqa: F401


class VideosShowcasesAddToMultipleShowcasesRequest(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        
        class properties:
        
            @staticmethod
            def add() -> typing.Type['VideosShowcasesAddToMultipleShowcasesRequestAdd']:
                return VideosShowcasesAddToMultipleShowcasesRequestAdd
        
            @staticmethod
            def remove() -> typing.Type['VideosShowcasesAddToMultipleShowcasesRequestRemove']:
                return VideosShowcasesAddToMultipleShowcasesRequestRemove
            __annotations__ = {
                "add": add,
                "remove": remove,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["add"]) -> 'VideosShowcasesAddToMultipleShowcasesRequestAdd': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["remove"]) -> 'VideosShowcasesAddToMultipleShowcasesRequestRemove': ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["add", "remove", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["add"]) -> typing.Union['VideosShowcasesAddToMultipleShowcasesRequestAdd', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["remove"]) -> typing.Union['VideosShowcasesAddToMultipleShowcasesRequestRemove', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["add", "remove", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        add: typing.Union['VideosShowcasesAddToMultipleShowcasesRequestAdd', schemas.Unset] = schemas.unset,
        remove: typing.Union['VideosShowcasesAddToMultipleShowcasesRequestRemove', schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'VideosShowcasesAddToMultipleShowcasesRequest':
        return super().__new__(
            cls,
            *args,
            add=add,
            remove=remove,
            _configuration=_configuration,
            **kwargs,
        )

from vimeo_python_sdk.model.videos_showcases_add_to_multiple_showcases_request_add import VideosShowcasesAddToMultipleShowcasesRequestAdd
from vimeo_python_sdk.model.videos_showcases_add_to_multiple_showcases_request_remove import VideosShowcasesAddToMultipleShowcasesRequestRemove
