# coding: utf-8

"""
    Vimeo API

    Build something great. Vimeo's API supports flexible, high-quality video integration with your custom apps.

    The version of the OpenAPI document: 3.4
    Created by: https://developer.vimeo.com/help
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from vimeo_python_sdk import schemas  # noqa: F401


class VideosVersionsAddVideoVersionRequest(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        required = {
            "upload",
            "file_name",
        }
        
        class properties:
            file_name = schemas.StrSchema
        
            @staticmethod
            def upload() -> typing.Type['VideosVersionsAddVideoVersionRequestUpload']:
                return VideosVersionsAddVideoVersionRequestUpload
            __annotations__ = {
                "file_name": file_name,
                "upload": upload,
            }
    
    upload: 'VideosVersionsAddVideoVersionRequestUpload'
    file_name: MetaOapg.properties.file_name
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["file_name"]) -> MetaOapg.properties.file_name: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["upload"]) -> 'VideosVersionsAddVideoVersionRequestUpload': ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["file_name", "upload", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["file_name"]) -> MetaOapg.properties.file_name: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["upload"]) -> 'VideosVersionsAddVideoVersionRequestUpload': ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["file_name", "upload", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        upload: 'VideosVersionsAddVideoVersionRequestUpload',
        file_name: typing.Union[MetaOapg.properties.file_name, str, ],
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'VideosVersionsAddVideoVersionRequest':
        return super().__new__(
            cls,
            *args,
            upload=upload,
            file_name=file_name,
            _configuration=_configuration,
            **kwargs,
        )

from vimeo_python_sdk.model.videos_versions_add_video_version_request_upload import VideosVersionsAddVideoVersionRequestUpload
