# coding: utf-8

"""
    Vimeo API

    Build something great. Vimeo's API supports flexible, high-quality video integration with your custom apps.

    The version of the OpenAPI document: 3.4
    Created by: https://developer.vimeo.com/help
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from vimeo_python_sdk import schemas  # noqa: F401


class WebinarEventMetadataConnections(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)

    A collection of information that is connected to this resource.
    """


    class MetaOapg:
        required = {
            "live_video",
            "team_member",
            "videos",
            "pre_live_video",
            "pictures",
        }
        
        class properties:
        
            @staticmethod
            def live_video() -> typing.Type['WebinarEventMetadataConnectionsLiveVideo']:
                return WebinarEventMetadataConnectionsLiveVideo
        
            @staticmethod
            def pictures() -> typing.Type['WebinarEventMetadataConnectionsPictures']:
                return WebinarEventMetadataConnectionsPictures
        
            @staticmethod
            def pre_live_video() -> typing.Type['WebinarEventMetadataConnectionsPreLiveVideo']:
                return WebinarEventMetadataConnectionsPreLiveVideo
        
            @staticmethod
            def team_member() -> typing.Type['WebinarEventMetadataConnectionsTeamMember']:
                return WebinarEventMetadataConnectionsTeamMember
        
            @staticmethod
            def videos() -> typing.Type['WebinarEventMetadataConnectionsVideos']:
                return WebinarEventMetadataConnectionsVideos
            __annotations__ = {
                "live_video": live_video,
                "pictures": pictures,
                "pre_live_video": pre_live_video,
                "team_member": team_member,
                "videos": videos,
            }
    
    live_video: 'WebinarEventMetadataConnectionsLiveVideo'
    team_member: 'WebinarEventMetadataConnectionsTeamMember'
    videos: 'WebinarEventMetadataConnectionsVideos'
    pre_live_video: 'WebinarEventMetadataConnectionsPreLiveVideo'
    pictures: 'WebinarEventMetadataConnectionsPictures'
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["live_video"]) -> 'WebinarEventMetadataConnectionsLiveVideo': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["pictures"]) -> 'WebinarEventMetadataConnectionsPictures': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["pre_live_video"]) -> 'WebinarEventMetadataConnectionsPreLiveVideo': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["team_member"]) -> 'WebinarEventMetadataConnectionsTeamMember': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["videos"]) -> 'WebinarEventMetadataConnectionsVideos': ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["live_video", "pictures", "pre_live_video", "team_member", "videos", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["live_video"]) -> 'WebinarEventMetadataConnectionsLiveVideo': ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["pictures"]) -> 'WebinarEventMetadataConnectionsPictures': ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["pre_live_video"]) -> 'WebinarEventMetadataConnectionsPreLiveVideo': ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["team_member"]) -> 'WebinarEventMetadataConnectionsTeamMember': ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["videos"]) -> 'WebinarEventMetadataConnectionsVideos': ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["live_video", "pictures", "pre_live_video", "team_member", "videos", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        live_video: 'WebinarEventMetadataConnectionsLiveVideo',
        team_member: 'WebinarEventMetadataConnectionsTeamMember',
        videos: 'WebinarEventMetadataConnectionsVideos',
        pre_live_video: 'WebinarEventMetadataConnectionsPreLiveVideo',
        pictures: 'WebinarEventMetadataConnectionsPictures',
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'WebinarEventMetadataConnections':
        return super().__new__(
            cls,
            *args,
            live_video=live_video,
            team_member=team_member,
            videos=videos,
            pre_live_video=pre_live_video,
            pictures=pictures,
            _configuration=_configuration,
            **kwargs,
        )

from vimeo_python_sdk.model.webinar_event_metadata_connections_live_video import WebinarEventMetadataConnectionsLiveVideo
from vimeo_python_sdk.model.webinar_event_metadata_connections_pictures import WebinarEventMetadataConnectionsPictures
from vimeo_python_sdk.model.webinar_event_metadata_connections_pre_live_video import WebinarEventMetadataConnectionsPreLiveVideo
from vimeo_python_sdk.model.webinar_event_metadata_connections_team_member import WebinarEventMetadataConnectionsTeamMember
from vimeo_python_sdk.model.webinar_event_metadata_connections_videos import WebinarEventMetadataConnectionsVideos
