# coding: utf-8

"""
    Vimeo API

    Build something great. Vimeo's API supports flexible, high-quality video integration with your custom apps.

    The version of the OpenAPI document: 3.4
    Created by: https://developer.vimeo.com/help
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from vimeo_python_sdk.type.update_webinar_request_email_settings import UpdateWebinarRequestEmailSettings
from vimeo_python_sdk.type.update_webinar_request_privacy import UpdateWebinarRequestPrivacy
from vimeo_python_sdk.type.update_webinar_request_schedule import UpdateWebinarRequestSchedule

class RequiredUpdateWebinarRequest(TypedDict):
    pass

class OptionalUpdateWebinarRequest(TypedDict, total=False):
    # The title of the webinar.
    title: str

    # The description of the webinar.
    description: str

    email_settings: UpdateWebinarRequestEmailSettings

    # The password when **privacy.view** is `password`. Anyone with the password can view the videos generated by streaming to the webinar event.
    password: str

    privacy: UpdateWebinarRequestPrivacy

    schedule: UpdateWebinarRequestSchedule

    # The status of the webinar.  Option descriptions:  * `ended` - The webinar has ended.  * `started` - The webinar has started. 
    status: str

    # The time zone used in resolving the timestamps that are included in the automatically generated video titles for the webinar.
    time_zone: str

class UpdateWebinarRequest(RequiredUpdateWebinarRequest, OptionalUpdateWebinarRequest):
    pass
